### ISSUE TITLE
TODO after merging classes: Repackaging

### ISSUE THREAD

**Issue by jahink17** [CSC207-2022F-UofT/course-project-studyhero#27]
Hi everyone! Looks like Victor was right -- we should be packaging our files according to our layers (e.g. Entities, Use Cases, UI etc.) instead of according to the features. Within each layer package, you can feel free to have further packaging according to features. E.g. - a possible file path could be: main/usecases/statsdisplay/statsdisplayinteractor.

I can make the layer packages once everyone's done merging their skeletons. After this is done, I'll tag y'all and each of you can put your classes in the corresponding packages.

**Comment by madelahn** [comment]
Sounds good, thank you Jahin! 👯 Let us know if you need any help.

**Comment by jahink17** [comment]
So I changed my mind about how we should go about this. It seems that I can't commit empty packages, so it wouldn't make sense for me to just add package names and then have everyone move their classes into appropriate packages. Instead, perhaps it's best for everyone to have the appropriate packaging on their next commit, and then once we merge to main we'll have our files in proper packages.

Just so the packaging is consistent, this is the format I suggest:
1. One entities package where we put all the entities
2. One screens package dealing with both the UI stuff and any interface adapter layer classes (e.g. controllers and presenters)
3. Use case packages (for e.g. I have a stats_display_use_case package)

I think this is the best way (for now) to have "packaging by use case" that the teaching team recommends, but let me know if y'all have alternate suggestions and we can discuss.

**Comment by jahink17** [comment]
Naming convention for package name: use lowercase and underscores e.g. stats_display_use_case

**Comment by AVLTG** [comment]
> So I changed my mind about how we should go about this. It seems that I can't commit empty packages, so it wouldn't make sense for me to just add package names and then have everyone move their classes into appropriate packages. Instead, perhaps it's best for everyone to have the appropriate packaging on their next commit, and then once we merge to main we'll have our files in proper packages.
> 
> Just so the packaging is consistent, this is the format I suggest:
> 
> 1. One "entities" package where we put all the entities
> 2. One "screens" package dealing with both the UI stuff and any interface adapter layer classes (e.g. controllers and presenters)
> 3. Use case packages (for e.g. I have a stats_display_use_case package)
> 
> I think this is the best way (for now) to have "packaging by use case" that the teaching team recommends, but let me know if y'all have alternate suggestions and we can discuss.

@jahink17 is it a requirement or a suggestion, because I think there would be a lot of issues with us updating the files this much. We would probably have to manually delete folders from main if it comes to it since now we have different directories that have different directories that have different names with the same files. I think if we merge that with main branch it might try to keep the old stuff and add the old stuff (since it will think we are ONLY adding new files) basically duplicating our files even though they are just in different directories now. I might be wrong though as I'm not exactly sure how gihub would deal with two files with the same name in different directories
