### ISSUE TITLE
Help with the settings menu

### ISSUE THREAD

**Issue by AVLTG** [CSC207-2022F-UofT/course-project-studyhero#35]
@CanaLeung Is there any chance you could help me with doing the settings menu a bunch? I think since you already implemented the save game and quit game buttons and functionalities, it would be best if you also implement them for the settings menu. I will work on the music player myself, unless you want to also help with that. I've been a little stumped with the boss fight so I'm not sure how much of my attention I can turn to the settings menu.

**Comment by madelahn** [comment]
I'm also able to help with the Settings menu while I wait for the different merges to the main branch for my feature.
We can look at Cana's implementations for the save and quit game buttons and just make similar buttons for the Settings Menu. I'm happy to help you with the Music Player, also :)

**Comment by AVLTG** [comment]
Thank you so much!!!
