### ISSUE TITLE
Testing on Entity Classes?

### ISSUE THREAD

**Issue by m1k2l3** [CSC207-2022F-UofT/course-project-studyhero#47]
Do we need to write tests for the entity classes? If so, which portion of the methods inside the entity classes should we test?

**Comment by madelahn** [comment]
I definitely recommend to test for it, but I don't think you need to test anything other getter/setter functions (if it's applicable to your class), since most of our tests should be around our methods in the input/output layers of our software.

**Comment by jfongli** [comment]
I agree with Maddie- I don't think there's much besides the getter/setter functions. Maybe some other tests to do would be if your entity updates in some form (like, "gold" for example).
